import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/header";
import MobilMenu from "@/components/mobilMenu";
import { MenuProvider } from "../context/MenuContext";
import ScrollProgres from "@/components/scrollProgres";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MenuProvider>
          <Header />
          {children}
          <MobilMenu />
          <ScrollProgres />
          <Footer />
        </MenuProvider>
      </body>
    </html>
  );
}
